{% set name = "pytest-raises" %}
{% set version = "0.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4710a8921b0b7425cd2073d696862ecf99922ef522e681cc63a52008112d63d9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - pytest >=3.2.2
    - python
    - setuptools
  run:
    - pytest >=3.2.2
    - python
    - setuptools

test:
  imports:
    - pytest_raises

about:
  home: https://github.com/Lemmons/pytest-raises
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of pytest.raises as a pytest.mark fixture
  doc_url: https://github.com/Lemmons/pytest-raises
  dev_url: https://github.com/Lemmons/pytest-raises

extra:
  recipe-maintainers:
    - DanielBok
